<?php
/**
 * banner
 *
 * @copyright Copyright © 2020 Landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */
?>


<div class="camera_wrap">
    <div data-src="1.jpg">
        <img src="">
        <div class="camera_caption">
            <p>Caption 1</p>
        </div>
    </div>
    <div data-src="2jpg">
        <img src="2.jpg">
        <div class="camera_caption">
            <p>Caption 2</p>
        </div>
    </div>
    <div data-src="3.jpg">
        <img src="3.jpeg">
        <div class="camera_caption">
            <p>Caption 3</p>
        </div>
    </div>
</div>
