<?php
/**
 * banner
 *
 * @copyright Copyright © 2020 Landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */
?>
<?php

$bannerCollection = $block->getBannerCollection();
$mediaUrl = $block->getMediaUrl();
$autoAdvance = $block->getAutoPlayConfig();
$effect = $block->getEffectConfig();
$interval = $block->getIntervalConfig();
$duration = $block->getDurationConfig();
$navigation = $block->getNavigationConfig();
$loader = $block->getLoaderConfig();
$pauseOnHover = $block->getPauseOnHoverConfig();
$buttonsPlayPause = $block->getPlayPauseButtonConfig();
$barPosition = $block->getBarPositionConfig();
$piePosition = $block->getPiePositionConfig();
?>

<?php


foreach ($bannerCollection as $banner) {
    $getImages = get_object_vars(json_decode($banner['images']));
    ?>
    <div id="camera_wrap_<?= $banner['banner_id'] ?>" data-id="<?= $banner['banner_id'] ?>"
         class="camera_slider">
        <?php
        foreach ($getImages as $image) {
            $imageUrl = $mediaUrl . $image;
            ?>
            <div id="lof-images" data-src="<?= $imageUrl ?>">
                <img src="<?= $imageUrl ?>">
                <?php
                if ($banner['show_banner_content'] == 1) {
                    ?>
                    <?php
                    if ($banner['show_banner_title'] == 1) {
                        ?>
                        <div class="lof-title">
                            <span class="lof-title-banner"><?= $banner['title'] ?></span>
                        </div>
                    <?php } ?>
                    <div class="camera_caption">
                        <p class="lof-description-banner"><?= $banner['description'] ?></p>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
    <script>
        require([
            'jquery',
        ], function ($) {
            "use strict";
            $(document).ready(function () {
                $(".camera_slider").click(function () {
                    window.location = "http://www.google.com/";
                });
            })
        })
    </script>
    <?php
}
?>

<style>
    .lof-title-banner {
        color: #ffffff;
        background: rgba(0, 0, 0, 0.8);
        line-height: 40px;
        padding: 10px;
        font-weight: bold;
    }
</style>


<script>
    require([
        'jquery',
        'Lof_CategoryBannerSlider/js/jquery.easing.1.3',
        'Lof_CategoryBannerSlider/js/camera.min'
    ], function ($) {
        "use strict";
        $(document).ready(function () {
            if (!window.loadedCamera) {
                $('.camera_slider').each(function () {
                    const dataId = $(this).attr('data-id');
                    const id = 'camera_wrap_' + dataId;
                    $('#' + id).camera({
                        fx: "<?= $effect ?>",
                        autoAdvance:<?= $autoAdvance ?>,
                        playPause: <?= $buttonsPlayPause ?>,
                        navigation: <?= $navigation ?>,
                        navigationHover: true,
                        hover: <?= $pauseOnHover ?>,
                        loader: '<?=$loader?>',
                        loaderColor: 'red',
                        loaderBgColor: '#222222',
                        loaderOpacity: 1,
                        loaderPadding: 0,

                        time: <?= $interval ?>,
                        transPeriod: <?= $duration ?>,
                        pagination: <?= $navigation ?>,
                        barPosition: '<?= $barPosition ?>',
                        piePosition: '<?= $piePosition ?>',
                    })
                })
                window.loadedCamera = 1;
            }
        })
    })
</script>